title: Documentation
default_lang: fr
author:
  name: null
  email: null
taxonomies:
  - category
  - tag
metadata:
  description: 'RTFM Skeleton'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
